import { interfaceWord } from "../interfaces";

export const words: interfaceWord[] = [
    {
        id: 0,
        name: "barco",
        desc: "Embarcación con el fondo cóncavo y con cubierta, en especial la de gran o medio tonelaje.",
        state: false,
    },
    {
        id: 1,
        name: "avestruz",
        desc: "Es un gran ave no voladora propia de Africa, aunque anteriormente también habitaban Oriente Medio.",
        state: false,
    },
    {
        id: 2,
        name: "automovil",
        desc: "Vehículo de motor con ruedas, diseñado para el transporte terrestre de personas o mercancías.",
        state: false,
    },
    {
        id: 3,
        name: "bicicleta",
        desc: "Vehículo de propulsión humana compuesto por dos ruedas alineadas.",
        state: false,
    },
    {
        id: 4,
        name: "guitarra",
        desc: "Instrumento musical de cuerda pulsada, compuesto por una caja de resonancia y un mástil.",
        state: false,
    },
    {
        id: 5,
        name: "television",
        desc: "Aparato electrónico que recibe señales de televisión y muestra imágenes y sonido en la pantalla.",
        state: false,
    },
    {
        id: 6,
        name: "computadora",
        desc: "Máquina electrónica programable capaz de procesar datos y realizar diversas tareas.",
        state: false,
    },
    {
        id: 7,
        name: "perro",
        desc: "Mamífero carnívoro domesticado de la familia de los canidos, criado como mascota o para trabajo.",
        state: false,
    },
    {
        id: 8,
        name: "gato",
        desc: "Mamífero carnívoro domesticado de la familia de los felinos, criado como mascota.",
        state: false,
    },
    {
        id: 9,
        name: "libro",
        desc: "Conjunto de hojas de papel, pergamino u otro material, escritas o impresas, sujetas por uno de sus extremos y protegidas por tapas.",
        state: false,
    },
    {
        id: 10,
        name: "silla",
        desc: "Asiento con respaldo, generalmente de cuatro patas, utilizado para sentarse.",
        state: false,
    },
    {
        id: 11,
        name: "mesa",
        desc: "Mueble formado por una superficie plana y horizontal, generalmente sostenida por una o varias patas.",
        state: false,
    },
    {
        id: 12,
        name: "telefono",
        desc: "Dispositivo de telecomunicacion diseñado para transmitir señales acusticas por medio de señales electricas.",
        state: false,
    },
    {
        id: 13,
        name: "ventana",
        desc: "Abertura en la pared de un edificio que permite el paso de luz y aire al interior.",
        state: false,
    },
    {
        id: 14,
        name: "planta",
        desc: "Ser vivo que, sin moverse, crece y se nutre de sustancias inorgánicas, generalmente por medio de la fotosíntesis.",
        state: false,
    },
    {
        id: 15,
        name: "lápiz",
        desc: "Instrumento de escritura o dibujo que consiste en una barra delgada de grafito o de una mina de otro material, rodeada de una funda de madera o de plástico.",
        state: false,
    },
    {
        id: 16,
        name: "cuchara",
        desc: "Utensilio de mesa con forma de cazo pequeño en un extremo y mango largo en el otro, utilizado para tomar alimentos líquidos o semisólidos.",
        state: false,
    },
    {
        id: 17,
        name: "pelota",
        desc: "Objeto esférico utilizado en diversos juegos y deportes, generalmente de goma, cuero o plástico inflado.",
        state: false,
    },
    {
        id: 18,
        name: "nube",
        desc: "Masa visible formada por partículas de agua o hielo suspendidas en la atmósfera.",
        state: false,
    },
    {
        id: 19,
        name: "sol",
        desc: "Estrella que constituye el centro del sistema planetario en el que se encuentra la Tierra, y que proporciona calor y luz.",
        state: false,
    },
    {
        id: 20,
        name: "luna",
        desc: "Satélite natural de la Tierra que se encuentra en órbita alrededor de ella.",
        state: false,
    },
    {
        id: 21,
        name: "camisa",
        desc: "Prenda de vestir que cubre el torso, generalmente con mangas y botones en la parte delantera.",
        state: false,
    },
    {
        id: 22,
        name: "pantalon",
        desc: "Prenda de vestir que cubre desde la cintura hasta los tobillos, con una pernera para cada pierna.",
        state: false,
    },
    {
        id: 23,
        name: "zapatos",
        desc: "Calzado que cubre el pie y parte del tobillo, generalmente con suela y tacón.",
        state: false,
    },
    {
        id: 24,
        name: "lentes",
        desc: "Accesorio óptico que se utiliza para corregir la visión o proteger los ojos.",
        state: false,
    },
    {
        id: 25,
        name: "taza",
        desc: "Recipiente pequeño con asa, generalmente utilizado para tomar líquidos calientes como el té o el café.",
        state: false,
    },
    {
        id: 26,
        name: "silla",
        desc: "Asiento con respaldo, generalmente de cuatro patas, utilizado para sentarse.",
        state: false,
    },
    {
        id: 27,
        name: "cuaderno",
        desc: "Libro formado por un conjunto de hojas en blanco o con líneas, utilizado para escribir o tomar apuntes.",
        state: false,
    },
    {
        id: 28,
        name: "reloj",
        desc: "Instrumento para medir el tiempo que suele llevarse en la muñeca o fijarse en la pared.",
        state: false,
    },
    {
        id: 29,
        name: "cafe",
        desc: "Bebida aromática y estimulante obtenida a partir de las semillas tostadas del cafeto.",
        state: false,
    },
];

export const getColorLetter: Record<string, string> = {
    yellow: "letter-yellow",
    green: "letter-green",
    grey: "letter-grey",
    null: "letter-null",
};
